config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :comments
  get 'sessions/new'

  get 'movies/all' => 'movies#all'
  get 'movies/all/:genre' => 'movies#all'

  resources :movies
  resources :users 

  root 'movies#index'
  get 'movie'  => 'movies#show'
  get 'review'  => 'reviews#show'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :comments,          only: [:new, :create, :destroy]

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
     before_filter :require_login, :only => [:new, :edit]

  

  # GET /movies
  # GET /movies.json
  def index
      # @movies=Movie.all
      # @movies = Movie.paginate(page: params[:page], :per_page =>4).order('created_at DESC').search(params[:search])
      if params[:search] == nil
        @movies = Tmdb::Movie.now_playing
      else 
        @search = Tmdb::Search.new
        @search.resource("movie")
        @search.query(params[:search])
        @movies = @search.fetch
      end
      @configuration = Tmdb::Configuration.new
      respond_to do |format|
          format.html
          format.js
      end
  # @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @configuration = Tmdb::Configuration.new
    #@comments = @movie.comments.paginate(page: params[:page], :per_page =>5)
    #@reviews= @movie.reviews.paginate(page: params[:page], :per_page =>5)
    @reviews = Review.where("movie_id=?", @movie['id']).paginate(page: params[:page], :per_page =>5)
  end
  
  # GET /movies/all
  def all
    if params['genre']
      @genre = Tmdb::Genre.detail(params['genre'])
      @maxPages = @genre.total_pages
      @pages = Array.new
      (1..@maxPages).each { |i| @pages.push(i) }
      @indexes = @pages.paginate(page: params[:page], :per_page=>1)
      if params[:page] != nil && params[:page].to_i != 1
        @page = params[:page].to_i
        @movies = @genre.get_page(@page).results
      else
        @movies = @genre.results
      end
    else
      @movies = Tmdb::Movie.popular
    end
    @configuration = Tmdb::Configuration.new
    @genres = Tmdb::Genre.list['genres']
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie review was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie review was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      #@movie = Movie.find(params[:id])
      @movie = Tmdb::Movie.detail(params[:id])
      @trailers = Tmdb::Movie.trailers(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :category, :release_date, :review, :name)
    end
   
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_bootstrap_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<% if @movie.errors.any? %>
  <div  class="alert alert-danger" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>    
      The form contains <%= pluralize(@movie.errors.count, "error") %>.
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

<% end %>
<div class="row">
  <div class="col-md-4 ">
      <div class="field">
          <%= f.label :title %>
          <%= f.text_field :title, :class => "form-control",:rows=>10%>
      </div>
      <div class="field">
          <%= f.label :category %>
          <%= f.text_field :category, :class => "form-control" %>
      </div>
      <div class="field">
        <%= f.label :release_date %></br>
        <%= f.date_select :release_date, { :start_year => 1920},:class=>"form-control"%>
     </div>
    <div class="field">
        <%= f.label :review %>
        <%= f.text_area :review , :class => "form-control"%>
    </div>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    <div class="actions">
        <%= f.submit 'Submit', :class =>"btn btn-warning btn-sm"%>
    </div>
<% end %>
  </div>
</div>

app/views/movies/_search.html.erb
<%= form_tag :controller => 'movies', :action => 'search', :method => 'get' do %>
    <%= text_field_tag :search, params[:search], :id => 'search_field' %>
   <%= submit_tag "Search", :name => nil %> 
    <%= link_to_function "Clear", "$('search_field').clear()" %>
  <% end %> 

app/views/movies/_search_results.html.erb
 <ul>
    <% @movies.each do |movie| %>
  <li><%= link_to movietitle, 
    :action => 'show', :id => movie.id  %></li>
  <% end %>
  </ul>

app/views/movies/all.html.erb
<div class="list row alert alert-info">
  <div class="col-md-3">
    <h3>Select category:</h3>
  </div>
  <div class="dropdown col-md-3">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
      <% if @genre == nil %>
        Categories
      <% else %>
        <%= @genre.name %>
      <% end %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <% @genres.each do |genre| %>
      <li role="presentation">
          <%= link_to genre['name'], "/movies/all/"+genre['id'].to_s, :role=>"menuitem", :tabindex=>"-1" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<% if @movies != nil %>
  <% if @indexes != nil %>
    <%= will_paginate @indexes %>
  <% end %>

  <% @movies.each do |movie| %>
          <div class="list row">
              <div class="col-md-2">
                <% if movie['poster_path'] %>
                    <%= image_tag("#{@configuration.base_url}w154#{movie['poster_path']}") %>
                <% else %>
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                <% end %>
              </div>
              
              <dl class="dl-horizontal col-md-9"> 
                  <dt>Title:</dt>            
                  <dd><%= movie['title'] %></dd>
          
                  <dt>Release date:</dt>
                  <dd>
                    <% if movie['release_date'].length != 0 %>
                        <%= movie['release_date'] %>
                    <% else %>
                        ---
                    <% end %>
                  <dd>
              
                  <dt>Rating:</dt>
                  <dd><%= movie['vote_average'] %> (<%= movie['vote_count'] %> votes)<dd>
              </dl>
              
          <%= link_to 'Show', movie_path(movie['id']), :class=>"btn btn-primary btn-sm col-md-1" %> 
          
      </div>
  <% end %>
  <% if @indexes != nil %>
    <%= will_paginate @indexes %>
  <% end %>
<% end %>

app/views/movies/edit.html.erb
<%= link_to '<< Back', movies_path, :class=>"btn btn-success btn-sm" %>
<%= link_to 'Show', @movie, :class=>"btn btn-primary btn-sm" %>

<h1>Editing movie review</h1>


<%= render 'form' %>

app/views/movies/index.html.erb
<div class="main">

</div>
<h1>
    Movie Reviews
</h1>

    <% @movies.each do |movie| %>
        <div class="list row">
            <div class="col-md-2">
                <% if movie['poster_path'] %>
                    <%= image_tag("#{@configuration.base_url}w154#{movie['poster_path']}") %>
                <% else %>
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                <% end %>
            </div>
            
            <dl class="dl-horizontal col-md-9"> 
                <dt>Title:</dt>            
                <dd><%= movie['title'] %></dd>
        
                <dt>Release date:</dt>
                <dd>
                    <% if movie['release_date'].length != 0 %>
                        <%= movie['release_date'] %>
                    <% else %>
                        ---
                    <% end %>
                <dd>
            
                <dt>Rating:</dt>
                <dd><%= movie['vote_average'] %> (<%= movie['vote_count'] %> votes)<dd>
            </dl>
            
        <%= link_to 'Show', movie_path(movie['id']), :class=>"btn btn-primary btn-sm col-md-1" %> 
        
    </div>
<% end %>

app/views/movies/new.html.erb
<%= link_to '<< Back', movies_path, :class=>"btn btn-success" %>
<h1>Add movie review</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<div>
  <% if @movie['poster_path'] %>
      <%= image_tag("#{@configuration.base_url}w154#{@movie['poster_path']}") %>
  <% else %>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
  <% end %>
</div>

<p>
  <strong>Title:</strong>
  <%= @movie['title'] %>
</p>

<p>
  <strong>Category:</strong>
  <% if @movie['genres'] != nil && @movie['genres'].length != 0 %>
    <% @loop = 0 %>
    <% @movie['genres'].each do |genre| %>
      <% if @loop != 0 %>
        , 
      <%end%>
      <%= genre['name'] %>
      <% @loop += 1 %>
    <% end %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie['vote_average'] %> (<%= @movie['vote_count'] %> votes)
</p>

<p>
  <strong>Release date:</strong>
  <% if @movie['release_date'].length != 0 %>
    <%= @movie['release_date'] %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Time:</strong>
  <% if @movie['runtime'] != nil && @movie['runtime'] != 0 %>
    <%= @movie['runtime'] %>  min.
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Homepage:</strong>
  <% @homepage = @movie['homepage'] %>
  <% if @homepage != nil && @homepage.length != 0 %>
    <%= @homepage %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Language:</strong>
  <% if @movie['original_language'] != nil && @movie['original_language'].length != 0 %>
    <%= @movie['original_language'] %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Spoken languages:</strong>
  <% if @movie['spoken_languages'] != nil && @movie['spoken_languages'].length != 0 %>
    <% @loop = 0 %>
    <% @movie['spoken_languages'].each do |language| %>
      <% if @loop != 0 %>
        , 
      <%end%>
      <%= language['name'] %>
      <% @loop += 1 %>
    <% end %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Companies:</strong>
  <% if @movie['production_companies'] != nil && @movie['production_companies'].length != 0 %>
    <% @loop = 0 %>
    <% @movie['production_companies'].each do |company| %>
      <% if @loop != 0 %>
        , 
      <%end%>
      <%= company['name'] %>
      <% @loop += 1 %>
    <% end %>
  <% else %>
    ---
  <% end %>
</p>

<p>
  <strong>Review:</strong>
  <% if @movie['overview'] != nil && @movie['overview'].length != 0 %>
    <%= @movie['overview'] %>
  <% else %>
    ---
  <%end%>
</p>


<hr>

<button type="button" class="btn btn-primary btn-sm" id="showButton">
  Show trailers
</button>
<div id="trailers">
  <% if @trailers['youtube'] != nil %>
    <% @trailers['youtube'].each do |trailer| %>
    <br><br>
      <p>
        <strong><%= trailer['name'] %></strong>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="//www.youtube.com/embed/<%= trailer['source'] %>"></iframe>
        </div>
      </p>
    <% end %>
  <% end %>
</div>

<hr>

<%= link_to '<< Back', movies_path, :class=>"btn btn-success btn-sm"%>

  <%= link_to 'Add review',  new_review_path(:movie => @movie['id']), :class=>"btn btn-primary btn-sm" %>


 <div>
    <% if @reviews.any? %>
      <h2>Review (<%= @reviews.count %>)</h2>
 
        <% @reviews.each do |review| %>
     <ul id="reviews">
        <li>Title: <%= review.title %> </li>
            <li><%= review.created_at.strftime("%m/%d/%Y") %></li>
        <li><%= link_to 'Show', review, :class=>"btn btn-primary btn-sm" %> 
         <% if logged_in? && review.user.name == current_user.name %>
           <%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm"%>
         <% end %> </li>
    </ul>
<% end %>
      <%= will_paginate @reviews %>
    <% end %>
    
  </div>

<script>
  var trailers = document.getElementById("trailers");
  var showButton = document.getElementById("showButton");
  
  trailers.style.display = "none";
  
  showButton.onclick = function(){
    if (trailers.style.display === "none"){
      trailers.style.display = "block";
      showButton.textContent = "Hide trailers";
    } else {
      trailers.style.display = "none";
      showButton.textContent = "Show trailers";
    }
  };
</script>