config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :comments
  get 'sessions/new'

  get 'movies/all' => 'movies#all'
  get 'movies/all/:genre' => 'movies#all'

  resources :movies
  resources :users 

  root 'movies#index'
  get 'movie'  => 'movies#show'
  get 'review'  => 'reviews#show'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :comments,          only: [:new, :create, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, :only => [:new, :edit]


  # GET /reviews/1
  # GET /reviews/1.json
  def show
      @comments= @review.comments.paginate(page: params[:page], :per_page =>5)
      @movie = Tmdb::Movie.detail(@review.movie_id)
     # @user=User.find(current_user)
  end

  # GET /reviews/new
  def new
    @review = Review.new
    #@movie=Movie.find(params[:movie])
    @movie = Tmdb::Movie.detail(params[:movie])
    @user=User.find(current_user)
  end

  # GET /reviews/1/edit
  def edit
     @movie = Tmdb::Movie.detail(@review.movie_id)
     @user=User.find(current_user)
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

   # respond_to do |format|
      if @review.save        
           flash[:success] = "You have created review successfully."
         redirect_to(movie_path(@review.movie_id))
      else
        @user=User.find(current_user)
        @movie = Tmdb::Movie.detail(@review.movie_id)
         flash.now[:danger] = 'Invalid data'
          render 'new'
      end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
      @movie = Tmdb::Movie.detail(@review.movie_id)
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        @user=User.find(current_user)
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    #respond_to do |format|
      flash[:notice] ='Movie review was successfully destroyed.'
       redirect_to(movie_path(@review.movie_id))
      #format.json { head :no_content }
  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :description, :movie_id, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
   <div  class="alert alert-danger" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>    
      The form contains <%= pluralize(@review.errors.count, "error") %>.
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-md-4 ">
      <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control",:rows=>10%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control"%>
  </div>
   <%= f.hidden_field :movie_id, :value => @movie['id'] %>
   <%= f.hidden_field :user_id, :value => @user.id %>
     <div class="actions">
        <%= f.submit 'Submit', :class =>"btn btn-warning btn-sm"%>
<% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= link_to '<< Back', movie_path(@movie['id']), :class=>"btn btn-success" %>
<%= link_to 'Show', @review, :class=>"btn btn-primary btn-sm" %>
<h1>Editing Review</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<%= link_to '<< Back', movie_path(@movie['id']), :class=>"btn btn-success" %>
<h1>Add movie review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<%= link_to '<< Back', movie_path(@movie['id']), :class=>"btn btn-success" %>
<br></br>
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @movie['title'] %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>



<% if logged_in? %>
  <% if @review.user.name == current_user.name %>
    <%= link_to 'Edit', edit_review_path(@review), :class =>"btn btn-warning btn-sm"%>
  <% end %>
<% end %>
  <%= link_to 'Add comment',  new_comment_path(:review => @review.id), :class=>"btn btn-primary btn-sm" %>


<% if @review.comments.any? %>
      <h2>Comments (<%= @review.comments.count %>)</h2>
      <ol class="comments">
        <%= render @review.comments %>
      </ol>
      <%= will_paginate @comments %>
    <% end %>